global:
    owner: paul.agada@regovtech.com
    qsname: TASKCAT
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - sa-east-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    reporting: true
  tests:
    test-scenario1:
      parameter_input: input.json
      template_file: appsync
      regions:
      - ap-southeast-1