project:
  name: my-cfn-project
  owner: paul.agada@regovtech.com
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
tests:
  default:
    template: ./templates/appsync.yml
    parameter_input: input.json
    template_file: appsync
    regions:
      - ap-southeast-1
      