version: 0.2
phases:
  install:
    commands:
      - echo "No any installation need for task" 
  build:
    commands:
      - echo "Nothing to build here in this task"    
  post_build:
    commands:
      - aws cloudformation package --template-file ./templates/appsync.yaml 
                                        --s3-bucket $DeploymentBucketName
                                        --output-template-file output.yml
                                        --region $AWS_DEFAULT_REGION
artifacts:
  type: zip
  files:
    - ./templates/appsync.yaml
    - output.yml