version: 0.1
phases:
  install:
    commands:
      - echo "No any installation need for task" 
  build:
    commands:
      - echo "Nothing to build here in this task"    
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml 
                                        --s3-bucket $DeploymentBucketName
                                        --output-template-file output.yml
                                        --region $AWS_DEFAULT_REGION
artifacts:
  type: zip
  files:
    - template.yml
    - output.yml